#!/usr/bin/env python3
"""Generate circuits/poseidon_gl/poseidon_gl_constants.circom from Plonky2's
ALL_ROUND_CONSTANTS + MDS_MATRIX_{CIRC,DIAG}.

Source: 0xPolygonZero/plonky2 @ v1.1.0 (Apache-2.0).
Round-constants extraction:
    awk '/pub const ALL_ROUND_CONSTANTS/,/^\\];/' plonky2/src/hash/poseidon.rs \\
      | grep -oE '0x[0-9a-fA-F]{16}' | tail -n +2  # skip doc-comment hex
MDS values are static and hand-copied from
    plonky2/src/hash/poseidon_goldilocks.rs (MDS_MATRIX_CIRC / MDS_MATRIX_DIAG).

Run: python3 tools/gen_poseidon_gl_constants/generate.py \\
        --in tools/gen_poseidon_gl_constants/all_round_constants.txt \\
        --out circuits/poseidon_gl/poseidon_gl_constants.circom
"""
import argparse
import textwrap
from pathlib import Path

WIDTH = 12
N_ROUNDS = 30
N_FULL_HALF = 4
N_PARTIAL = 22
SBOX = 7

MDS_CIRC = [17, 15, 41, 16, 2, 28, 13, 13, 39, 18, 34, 20]
MDS_DIAG = [8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

HEADER = """\
pragma circom 2.2.3;

// Plonky2 Goldilocks Poseidon constants.
//
// Source: 0xPolygonZero/plonky2 @ v1.1.0 (Apache-2.0), specifically:
//   plonky2/src/hash/poseidon.rs  : ALL_ROUND_CONSTANTS[u64; 360] (12*30)
//   plonky2/src/hash/poseidon_goldilocks.rs : MDS_MATRIX_CIRC[12], MDS_MATRIX_DIAG[12]
//
// Permutation params:
//   t = WIDTH = 12
//   full rounds = 8 (4 + 4)
//   partial rounds = 22
//   total rounds = 30
//   S-box exponent = 7
//
// MDS layer convention (full + partial — see plonky2 mds_row_shf):
//   result[r] = sum_i state[(i + r) mod 12] * MDS_CIRC[i] + state[r] * MDS_DIAG[r]
//
// Generated by tools/gen_poseidon_gl_constants/generate.py.
// DO NOT EDIT BY HAND — regenerate to pick up upstream changes.
"""


def emit_2d_array(values: list[int]) -> str:
    """Format a 12-per-round, 30-row array as Circom literal."""
    assert len(values) == WIDTH * N_ROUNDS, f"expected {WIDTH*N_ROUNDS}, got {len(values)}"
    rows = []
    for r in range(N_ROUNDS):
        row = values[r * WIDTH : (r + 1) * WIDTH]
        formatted = ", ".join(f"0x{v:016x}" for v in row)
        rows.append(f"        [{formatted}]")
    return "[\n" + ",\n".join(rows) + "\n    ]"


def emit_1d_array(values: list[int]) -> str:
    return "[" + ", ".join(str(v) for v in values) + "]"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--in", dest="input", required=True, type=Path)
    parser.add_argument("--out", dest="output", required=True, type=Path)
    args = parser.parse_args()

    with args.input.open() as f:
        lines = [line.strip() for line in f if line.strip()]
    values = [int(line, 16) for line in lines]
    assert len(values) == WIDTH * N_ROUNDS, (
        f"expected {WIDTH*N_ROUNDS} round constants, got {len(values)}"
    )

    body = textwrap.dedent(
        f"""\
        function getPoseidonGlRoundConstants() {{
            return {emit_2d_array(values)};
        }}

        function getPoseidonGlMdsCirc() {{
            return {emit_1d_array(MDS_CIRC)};
        }}

        function getPoseidonGlMdsDiag() {{
            return {emit_1d_array(MDS_DIAG)};
        }}
        """
    )
    args.output.write_text(HEADER + "\n" + body)
    print(f"Wrote {args.output} ({len(values)} round constants, MDS_CIRC, MDS_DIAG).")


if __name__ == "__main__":
    main()
